### ISSUE TITLE
新版本的 Vortex 已经更换翻译文件的路径了

### ISSUE THREAD

**Issue by cathaysia** [liuyanxi975/Chinese-Translation-for-Vortex#3]
![图片](https://user-images.githubusercontent.com/42114817/91851224-63fa9100-ec91-11ea-83ca-a19c127d059c.png)

如图，在 Vortex 1.3.2 beta 中，翻译文件的路径已经被更改到 C:\ProgramData\Vortex\plugins\ 下。

json 里的内容是我抄的日语翻译中的，因为 vortex 可以自动下载语言文件（但是还不支持中文）。内容如下：

```json
{
  "name": "Chinese Translation for Vortex",
  "author": "liuyanxi975",
  "version": "1.2.15",
  "description": "This file is Chinesetranslation for Vortex. This file contains locales/zh/*.json files.",
  "type": "translation",
  "bundled": false,
  "modId": 32
}
```

**Comment by liuyanxi975** [comment]
你好，最近有些忙，很抱歉这么晚回复。
关于路径问题：我注意到如果手动安装，原来的路径没有更改，依旧生效。
对于自动下载：这应该是官方的行为，官方选定了一些翻译文件，制作成了插件，使得它们可以被Vortex自动下载和安装。这个info.json似乎不需要翻译者手动编辑和上传（因为我没看见其它翻译者的翻译文件中包括它）。
事实上这个问题已经由Vortex开发者Tannin42提醒过我，因为我上传的文件包含了多余的目录，他说这可能导致Vortex无法自动安装翻译，当时还没有自动安装这个功能。。后来我脑残又忘了这茬，当然今天的新版本已经解决了这个问题，并且我已经向Tannin42说明。可能之后，Vortex的中文翻译就会被安排自动安装，这应该取决于官方。
附我和Tannin42的对话

> Tannin42 (08 May 2020, 6:53PM): The latest version from 08 May 2020 is not packaged correctly to be installed by Vortex automatically. Please read the wiki for packaging Vortex translations: https://wiki.nexusmods.com/index.php/Packaging_extensions_for_Vortex  . the tl;dr is: the top-level directory inside the archive has to be the iso code of the language, in the current package the top-level dir is called "Vortex?????????"

> Me (08 May 2020, 7:29PM): Thanks for the reminder, I've re-uploaded.

> Tannin42 (15 June 2020, 4:23PM): Same problem with the June 15th update

> Me (24 October 2020, 3:14PM): Sorry, I forgot. The new version has solved the problem.
