### ISSUE TITLE
更新 1.4.16 版本翻译

### ISSUE THREAD

**Issue by CatofTang** [liuyanxi975/Chinese-Translation-for-Vortex#9]
![未翻译部分](https://user-images.githubusercontent.com/39953740/150661189-a70b1a85-327a-4cf5-aba6-9044278bdfc7.jpg)
已更新至 1.4.16 ，部分翻译缺失，烦请更新翻译 :-）

**Comment by liuyanxi975** [comment]
在做了在做了。。。十分抱歉，真的太忙了。。我努力在春节期间完成更新。。

**Comment by liuyanxi975** [comment]
2020/1/29更新：
1.5.0版本已在github上传。
releases下载：https://github.com/liuyanxi975/Chinese-Translation-for-Vortex/releases/tag/1.5.0
